webco_flow:
  image: webandco/ubuntu-supervisor-appserver-typo3

  ports:
    - 80:80
    - 443:443
    - 9080:9080
    - 9443:9443

  environment:
    - APPSERVER_PHP_MEMORY_LIMIT=512M
    - APPSERVER_VHOST_DOMAIN=xxx.local
